<?php

namespace AppBundle\Repository;

/**
 * ArticleChildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleChildRepository extends \Doctrine\ORM\EntityRepository
{
}
