<?php

namespace AppBundle\Repository;

/**
 * FirstEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirstEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
